# This is a basic workflow to help you get started with Actions
# {think}: {3.14159}
name:head
# ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%mem | head
# Controls when the workflow will run
 # {on}: -brain=Ai.yml
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:$ talk‘user@host’ [ttyname]
   # branches: [ main ]
  # pull_request: 
    #branches: { main }
# $ talk‘user@host’ [ttyname]
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:
# mtr google.com
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs: 
  # This workflow contains a single job called "build"
  # build: 1.0
    # The type of runner that the job will run on
    # runs-on: [ ? ]

    # -()Ctrl-x-e Steps represent a sequence of tasks that will be executed as part of the job
    #steps: Ctrl-x-e
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
